FROM centos:7

MAINTAINER systeembeheer@nepworldwide.nl

##
# Install nginx mainline and base dependencies

RUN echo 'Europe/Amsterdam' > /etc/timezone \
 && rm -f /etc/localtime \
 && ln -vs /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime \
 && yum -y install epel-release \
 && curl -so /etc/pki/rpm-gpg/RPM-GPG-KEY-NGINX http://nginx.org/keys/nginx_signing.key \
 && echo -e '\
[nginx]\n\
name=nginx repo\n\
baseurl=http://nginx.org/packages/mainline/centos/7/x86_64/\n\
gpgcheck=1\n\
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-NGINX\n\
enabled=1' > /etc/yum.repos.d/nginx.repo\
 && yum -y install \
     curl \
     nginx \
 && rm -f /etc/yum.repos.d/nginx.repo /etc/pki/rpm-gpg/RPM-GPG-KEY-NGINX \
 && rm -rf /etc/nginx/conf.d/* \
 && mkdir -pv /var/www/html \
 && curl --silent --location https://rpm.nodesource.com/setup_6.x | bash - \
 && yum -y install \
     bzip2 \
     git \
     ruby ruby-devel \
     python python-devel \
     nodejs \
     gcc \
     gcc-c++ \
     make \
     gettext \

##
# Set this to prevent JSPM from locking up
 && echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config \
#
##

 && gem install compass sass --no-ri --no-rdoc \
 && curl -Lo /usr/bin/confd https://github.com/kelseyhightower/confd/releases/download/v0.12.0-alpha3/confd-0.12.0-alpha3-linux-amd64 \
 && chmod +x /usr/bin/confd \
 && yum -y remove epel-release nodesource-release \
 && yum clean all \
 && rm -rf /var/cache/yum/* \
 && find /var/log -type f -exec truncate -s 0 {} \;

COPY files/html/env.js              /var/www/html/env.js
COPY files/html/favicon.ico         /var/www/html/favicon.ico
COPY files/html/index.html          /var/www/html/index.html
COPY files/nginx/nginx.conf         /etc/nginx/nginx.conf
COPY files/nginx/001-logformat.conf /etc/nginx/conf.d/001-logformat.conf
COPY files/confd                    /etc/confd
COPY files/scripts.test/run.sh      /opt/run.sh

WORKDIR "/var/www/html"
EXPOSE 80 443
ENTRYPOINT ["/opt/run.sh"]
